//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteratureWritten.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Editions()
        {
            this.SubscribedEditions = new HashSet<SubscribedEditions>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> EditionType { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Price { get; set; }
    
        public virtual EditionType EditionType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscribedEditions> SubscribedEditions { get; set; }
    }
}
