//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteratureWritten.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditionReceiving
    {
        public int SubEdID { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual SubscribedEditions SubscribedEditions { get; set; }
    }
}
